name: Manage AutoTransform

on:
  workflow_dispatch:

jobs:
  manage-autotransform:
    runs-on: ubuntu-latest
    name: Manage AutoTransform
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install requirements
      run: pip install -r autotransform/requirements.txt
    - name: Manage AutoTransform
      run: autotransform manage --verbose
      env:
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}